/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2023-01-11 07:06:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class head_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/ahj/pro04/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro04/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1673336873466L));
    _jspx_dependants.put("jar:file:/D:/ahj/pro04/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro04/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/ahj/pro04/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro04/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 문서 정보 : 메타포(metaphor) -->\r\n");
      out.write("    <meta name=\"application-name\" content=\"HJpoto\">\r\n");
      out.write("    <meta name=\"subject\" content=\"HJpoto\">\r\n");
      out.write("    <meta name=\"keywords\" content=\"다양한 사진 감상 및 구매\">\r\n");
      out.write("    <meta name=\"description\" content=\"HJpoto는 다양한 사진을 감상할 수 있으며, 구매할 수 있습니다.\">\r\n");
      out.write("    <meta name=\"url\" content=\"https://hyojun-a.github.io/web04\">\r\n");
      out.write("    <meta name=\"author\" content=\"ahn hyo jun\">\r\n");
      out.write("    <meta name=\"email\" content=\"wnsgy79@gmail.com\">\r\n");
      out.write("    <meta name=\"robots\" content=\"index, flow\">\r\n");
      out.write("\r\n");
      out.write("    <!-- 오픈 그래프 -->\r\n");
      out.write("    <meta property=\"og:type\" content=\"website\">\r\n");
      out.write("    <meta property=\"og:url\" content=\"https://hyojun-a.github.io/web04\">\r\n");
      out.write("    <meta property=\"og:title\" content=\"HJpoto\">\r\n");
      out.write("    <meta property=\"og:site_name\" content=\"HJpoto\">\r\n");
      out.write("    <meta property=\"og:image\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/logo.png\">\r\n");
      out.write("    <meta property=\"og:image:width\" content=\"1000\">\r\n");
      out.write("    <meta property=\"og:image:height\" content=\"400\">\r\n");
      out.write("    <meta property=\"og:locale\" content=\"ko_KR\">\r\n");
      out.write("    <meta name=\"twitter:card\" content=\"video\">\r\n");
      out.write("    <meta name=\"twitter:title\" content=\"HJpoto\">\r\n");
      out.write("    <meta name=\"twitter:description\" content=\"HJpoto는 다양한 사진을 감상할 수 있으며, 구매할 수 있습니다.\">\r\n");
      out.write("    <meta name=\"twitter:image\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/logo.png\">\r\n");
      out.write("\r\n");
      out.write("    <!-- 기기의 지원 해상도별 아이콘 설정 -->\r\n");
      out.write("    <link rel=\"icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/logo.png\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 해상도 및 브라우저와 기기별 앱 아이콘 및 바로가기 아이콘 설정 -->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"favicon.ico\">\r\n");
      out.write("    <!-- 애플사의 기기 아이콘 설정 -->\r\n");
      out.write("    <meta name=\"apple-mobile-web-app-title\" content=\"HJpoto\">\r\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/logo.png\">\r\n");
      out.write("    <!-- 애플사 기기의 URL바나 UI바 보이게 -->\r\n");
      out.write("    <meta name=\"apple-mobile-web-app-capable\" href=\"yes\">\r\n");
      out.write("    <!-- 상태바의 색상 설정 -->\r\n");
      out.write("    <meta name=\"apple-mobile-web-app-status-bar-style\" href=\"black-translucent\">\r\n");
      out.write("    <!-- MS 사의 기기에 대한 아이콘 설정-->\r\n");
      out.write("    <meta name=\"msapplication-TileColor\" content=\"#FFFFFF\">\r\n");
      out.write("    <meta name=\"msapplication-TileImage\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/logo.png\"><!-- 문서 정보 : 메타포(metaphor) -->\r\n");
      out.write("    <meta name=\"application-name\" content=\"HJpoto\">\r\n");
      out.write("    <meta name=\"subject\" content=\"HJpoto\">\r\n");
      out.write("    <meta name=\"keywords\" content=\"사진, 전시관\">\r\n");
      out.write("    <meta name=\"description\" content=\"HJpoto는 다양한 사진을 감상 및 구매 하실수 있습니다.\">\r\n");
      out.write("    <meta name=\"url\" content=\"https://hyojun-a.github.io/web04\">\r\n");
      out.write("    <meta name=\"author\" content=\"ahn hyo jun\">\r\n");
      out.write("    <meta name=\"email\" content=\"wnsgy79@gmail.com\">\r\n");
      out.write("    <meta name=\"robots\" content=\"index, flow\">\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/logo.png\">\r\n");
      out.write("\r\n");
      out.write("    <!-- 오픈 그래프 -->\r\n");
      out.write("    <meta property=\"og:type\" content=\"website\">\r\n");
      out.write("    <meta property=\"og:url\" content=\"https://hyojun-a.github.io/web04\">\r\n");
      out.write("    <meta property=\"og:title\" content=\"HJpoto\">\r\n");
      out.write("    <meta property=\"og:site_name\" content=\"HJpoto\">\r\n");
      out.write("    <meta property=\"og:image\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/logo.png\">\r\n");
      out.write("    <meta property=\"og:image:width\" content=\"1000\">\r\n");
      out.write("    <meta property=\"og:image:height\" content=\"400\">\r\n");
      out.write("    <meta property=\"og:locale\" content=\"ko_KR\">\r\n");
      out.write("    <meta name=\"twitter:card\" content=\"video\">\r\n");
      out.write("    <meta name=\"twitter:title\" content=\"HJpoto\">\r\n");
      out.write("    <meta name=\"twitter:description\" content=\"HJpoto는 다양한 사진을 감상 및 구매 하실수 있습니다.\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 해상도 및 브라우저와 기기별 앱 아이콘 및 바로가기 아이콘 설정 -->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"favicon.ico\">\r\n");
      out.write("    <!-- 애플사의 기기 아이콘 설정 -->\r\n");
      out.write("    <meta name=\"apple-mobile-web-app-title\" content=\"대준신발\">\r\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/logo.png\">\r\n");
      out.write("    <!-- 애플사 기기의 URL바나 UI바 보이게 -->\r\n");
      out.write("    <meta name=\"apple-mobile-web-app-capable\" href=\"yes\">\r\n");
      out.write("    <!-- 상태바의 색상 설정 -->\r\n");
      out.write("    <meta name=\"apple-mobile-web-app-status-bar-style\" href=\"black-translucent\">\r\n");
      out.write("    <!-- MS 사의 기기에 대한 아이콘 설정-->\r\n");
      out.write("    <meta name=\"msapplication-TileColor\" content=\"#FFFFFF\">\r\n");
      out.write("    <meta name=\"msapplication-TileImage\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/logo.png\">\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-latest.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/css/foundation.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/motion-ui/1.2.3/motion-ui.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/css/foundation-prototype.min.css\">\r\n");
      out.write("<link href='https://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css' rel='stylesheet' type='text/css'>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/js/foundation.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/motion-ui/1.2.3/motion-ui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/ckeditor/ckeditor.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write(".title-bar-left img{ height: 40px;}\r\n");
      out.write(".off-canvas-absolute { background-color: #0a0a0a;}\r\n");
      out.write(".acolor {color:#FEFEFE; text-decoration:none}\r\n");
      out.write("#acolor {color:#FEFEFE;}\r\n");
      out.write("#ft { background-color: #0a0a0a;}\r\n");
      out.write(".content { width: 1330px; margin-top: 50px; background-color: #FEFEFE;}\r\n");
      out.write(".content1 { width: 1330px; margin-top: 50px; background-color: #FEFEFE;}\r\n");
      out.write("#smenu { width: 100%;}\r\n");
      out.write("#footer { position:fixed; bottom:0; z-index:100000; width: 100%;}\r\n");
      out.write("#smenu { width: 100%;  height: 100%;  background-color: #0a0a0a;}\r\n");
      out.write("	html,body {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 95%;\r\n");
      out.write("      }\r\n");
      out.write("    .mung { color:#FEFEFE; text-align: center; font-family: fantasy; font-weight: 200;} \r\n");
      out.write(".login-center {\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	width: 1000px;\r\n");
      out.write("	display: block;\r\n");
      out.write("	float: left;\r\n");
      out.write("}\r\n");
      out.write(".login-center:after { content=\"\"; display: block; clear: both;}\r\n");
      out.write(".login input{\r\n");
      out.write("	width: 200px;\r\n");
      out.write("	height: 25px;\r\n");
      out.write("	float: left;\r\n");
      out.write("	margin-right: 20px;\r\n");
      out.write("	margin-top: 8px;\r\n");
      out.write("}\r\n");
      out.write(".wrap {width: 90%; margin: 0 auto;} \r\n");
      out.write(".table1 { width: 100%; height: auto; border: 1px solid skyblue;  padding: 30px; text-align: left;}\r\n");
      out.write(".q_title { font-size: 22px; color: #111; font-weight: 500; margin-bottom: 20px; line-height: 24px; display: block;}\r\n");
      out.write(".q_content { line-height: 24px;}\r\n");
      out.write(".q_date { display: block; margin-top: 20px;}\r\n");
      out.write("</style>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/include/head.jsp(84,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path1");
      // /WEB-INF/views/include/head.jsp(84,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/include/head.jsp(84,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
